[project]
name = "projet-ro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gurobipy>=13.0.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pyqt6>=6.10.1",
]
